LOCAL_PATH := $(call my-dir)

# Phone
include $(CLEAR_VARS)
LOCAL_MODULE := Phone
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Dialer/Phone.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/priv-app
LOCAL_OVERRIDES_PACKAGES := Dialer dialer phone
include $(BUILD_PREBUILT)
